Improvement/lims 1163/improve error message when token is invalid
DiamondLightSource/SynchWeb pull request #702
Opened 2023-12-05 16:49 UTC by ndg63276

**JIRA ticket**: [LIMS-1163](https://jira.diamond.ac.uk/browse/LIMS-1163)

**Summary**:

Users complain of not being allowed to print an air waybill after booking a shipment into Diamond.

**Changes**:
- Specify in the error message generated whether this is because the one time token is too old, or non-existent
- Add user agent and timestamp to the error message generated
- Allow increasing of 10 second age limit with an optional config variable

**To test**:
- Generate an AWB for a shipment, check can view it from the shipment page
- Set a $max_token_age = -1 config variable and check the error generated (delete it afterwards)
- View a visit pdf report and CSV download from /visits page, as these also use the sign function

2023-12-14 16:57 UTC, MattPrit requested changes

2023-12-14 16:57 UTC, MattPrit commented on api/src/Controllers/AuthenticationController.php
> +                'timestamp' => gmdate('c', time())
I don't think we need to return these to the user. I think we should instead just log these when we log the auth token failure error and reason.

2023-12-14 16:57 UTC, MattPrit commented on api/src/Controllers/AuthenticationController.php
> +                    $err = 'Authorisation token not valid for this URL.';
I'm not sure that we would want to tell the user this. Perhaps we should, if a valid token is not found, return a more generic message to the user, e.g. "Invalid one-time authorization token, please go back and try again...", but log the reason internally.

2023-12-14 16:57 UTC, MattPrit commented on api/src/Controllers/AuthenticationController.php
> +        global $max_token_age;
I'm not convinced that there is a need to make this configurable. Perhaps we should wait until error logs suggest that the max token age is responsible for errors?

2024-01-10 09:43 UTC, gfrn commented on api/src/Controllers/AuthenticationController.php
> +                    $err = 'Authorisation token too old. Age: '.$token['AGE'].'s. Max age: '.$max_token_age.'s.';
I don't think this information should be returned to the user

2024-01-10 16:28 UTC, merged