LIMS-1170: Don't use thumbnails of crystal snapshot images
DiamondLightSource/SynchWeb pull request #703
Opened 2023-12-11 12:20 UTC by benjaminhwilliams

**JIRA ticket**: [LIMS-1170](https://jira.diamond.ac.uk/browse/LIMS-1170)

**Summary**:

Use full-sized crystal snapshot image files, not thumbnails.

Note that I have only touched the crystal snapshot image handling, not [the diffraction preview image handling](https://github.com/benjaminhwilliams/SynchWeb/blob/1eb0710e31bf045bf4f8608c8c67264a21d5e234/api/src/Page/Image.php#L261), which also uses a thumbnail image, which is generated upstream by a different mechanism to the snapshot image thumbnails.

**Changes**:
- Remove ternary operation to switch between reading the full-sized image and the thumbnail.  Always use the full-sized image.

**To test**:
- Find a data collection that has multiple image snapshots (each DC can have up to four).
- Open all views that display a data collection pane.  Check that the snapshot image is displayed correctly.
- Click on the snapshot image.  Check that you can still roll through the full selection of available snapshot images.
- Repeat the above for a robot load pane.

2024-01-25 14:59 UTC, benjaminhwilliams commented
@ndg63276, sorry, I dropped this earlier.  Can I add you as a reviewer or, alternatively, could you nominate someone suitable?  And/or, could you provide guidance on testing this myself?

2024-01-25 15:39 UTC, ndg63276 commented
Happy to have a look at it. Everything seems to work, but given that we are removing the use of the 'f' flag in data collection/robot action snapshot requests, can we get rid of the "/f/1" in lots of places?

ie the result of `grep 'image/id\|image/ai' -r client/src/js/* | grep "/f/1"`

2024-02-07 13:32 UTC, ndg63276 commented on api/src/Page/Image.php
> +                if (file_exists($images[$n])) {
Given that we are removing the use of the 'f' flag in data collection/robot action snapshot requests, can we get rid of the "/f/1" in lots of places?

2024-02-07 13:33 UTC, ndg63276 requested changes
Given that we are removing the use of the 'f' flag in data collection/robot action snapshot requests, can we get rid of the "/f/1" in lots of places?

2024-02-07 15:05 UTC, benjaminhwilliams commented
Thanks for the prod, @ndg63276, I agree and I'll make it happen ASAP.

2024-06-11 14:27 UTC, ndg63276 commented
Superseded by https://github.com/DiamondLightSource/SynchWeb/pull/784

2024-06-11 14:27 UTC, closed without merging