Handle -ve rotations, null overlap in sm/DC
DiamondLightSource/SynchWeb pull request #730
Opened 2024-02-15 16:18 UTC by ndevenish

~**JIRA ticket**: [TICKET-123](https://link.to.jira)~

**Summary**:

I19 is now doing small molecule serial, where every other collection is run with backwards oscillation. Unfortunately, recording this accurately in ISPyB doesn't show the autoprocessing sections in Synchweb.

This changes the check to be truthy (nonzero) instead of purely positive.

Also fixes an adjacent issue where a null value for overlap was passing the intended non-zero check (null != 0). This is made truthy also.

**Changes**:
- Altered data checks to check truthiness instead of comparisons to zero

**To test**:
- Viewing https://ispyb.diamond.ac.uk/dc/visit/cy35300-1/dcg/11242587 should show "Auto Processing" for both collections, instead of the current situation:
![image](https://github.com/DiamondLightSource/SynchWeb/assets/529963/e30ff28f-061a-4384-9400-2a5c6bddd6a7)

2024-02-16 12:23 UTC, ndg63276 commented on client/src/js/templates/types/sm/dc/dc.html
> +    <% if (AXISRANGE) { %>
```suggestion
    <% if (parseFloat(AXISRANGE)) { %>
```

2024-02-16 12:24 UTC, ndg63276 commented on client/src/js/templates/types/sm/dc/dc.html
> +        <% if (OVERLAP) { %>
```suggestion
        <% if (parseFloat(OVERLAP)) { %>
```

2024-02-16 12:25 UTC, ndg63276 requested changes
The values appear to be strings, so even zeroes are truthy.

2024-02-21 09:51 UTC, ndevenish commented
This appears to work fine!
![image](https://github.com/DiamondLightSource/SynchWeb/assets/529963/936ef8d3-d3ae-4671-b661-366d9f48c7db)

2024-02-21 09:52 UTC, ndg63276 approved these changes

2024-02-22 13:22 UTC, merged